### ISSUE TITLE
TimeoutError: The read operation timed out

### ISSUE THREAD

**Issue by seevee** [wingrunr21/hassio-xcel-itron-mqtt#4] opened 2024-01-06 16:59 UTC
For the last two nights, I've had this addon crash overnight.

Yesterday, I was able to restart addon without issue, but I have tried to restart today and am getting this error immediately and consistently now.

I suspect this is the meter misbehaving/disconnecting from wifi, but figured we can track this issue here as well.

<details>
<summary>
logs (crash occurred ~2hrs after starting):
</summary>

```
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[22:05:26] INFO: Starting Xcel iTron2MQTT
Connected to MQTT Broker!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1411, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 324, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1249, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='meter_ip', port=8081): Read timed out. (read timeout=4.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 81, in <module>
    meter.run()
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 229, in run
    obj.run()
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 172, in run
    reading = self.get_reading()
              ^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 79, in get_reading
    response = self.query_endpoint()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 42, in query_endpoint
    x = self.requests_session.get(self.url, verify=False, timeout=4.0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='meter_ip', port=8081): Read timed out. (read timeout=4.0)
[00:44:22] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service xcel-itron-mqtt: stopping
s6-rc: info: service xcel-itron-mqtt successfully stopped
s6-rc: info: service init-xcel-itron-mqtt: stopping
s6-rc: info: service init-xcel-itron-mqtt successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

</details>

**Comment by wingrunr21** [comment] 2024-01-07 16:07
Hi,

There's an open issue at @zaknye's tracking this as well. Right now it seems it's something to do with the meter firmware:

zaknye/xcel_itron2mqtt#22

**Comment by rbray89** [comment] 2024-01-18 10:39
This could be worked-around in the addon by modifying the finish script to not invoke halt.

The addon watchdog will NOT restart the addon if it exits too frequently, so we need to handle it more gracefully.

**Comment by wingrunr21** [comment] 2024-01-18 15:15
I'm not following. The upstream project itself will fail when a timeout occurs. Their solution is to just set Docker to restart until the meter timeouts are corrected. There are no options other than restarting here without a change upstream.

**Comment by rbray89** [comment] 2024-01-18 17:31
I get the s6 philosophy,  but I'd also like to not micromanage my services to ensure they stay up.

https://github.com/wingrunr21/hassio-xcel-itron-mqtt/blob/6263ae6ff04f511b704435556768b7f37042a253/xcel-itron-mqtt/rootfs/etc/s6-overlay/s6-rc.d/xcel-itron-mqtt/finish#L26C32-L26C32

Comment out the halt, and the service *should* be restarted according to S6 docs. Once the issue is fixed upstream, the change can be reverted.

Alternatively we can dig into the other repository and fix it there properly, but this was a shorter put.

**Comment by wingrunr21** [comment] 2024-01-18 19:24
So that will keep the container from stopping, yes, but it doesn't fix the connection to the meter. You'd still need to look at the logs and manually restart

**Comment by rbray89** [comment] 2024-01-18 19:39
wouldn't it restart the itron reading service?

**Comment by wingrunr21** [comment] 2024-01-18 19:52
Maybe? I'd need to try it. In theory it would but I think I'd need to delete the whole `finish` script (as there isn't a point in writing out the exit code if we aren't going to finish).

The other issue would be if the container ends up spinning it could cause some high CPU. I'd prefer something like a backoff retry strategy so the container will eventually stop. That wouldn't be terrible to add but it's just layering over what should just be a fix in the base project.

**Comment by wingrunr21** [comment] 2024-01-20 21:36
I have opened zaknye/xcel_itron2mqtt#24 to add some resiliency upstream

**Comment by mlapida** [comment] 2024-02-01 00:24
I’m seeing this issue too. Any reason why the watchdog doesn’t automatically restart the add-on?

**Comment by rbray89** [comment] 2024-02-01 04:26
@mlapida it does... the issue is that there's a limit to the number of retries the WD performs in a small time frame. Because the error is a HW/FW issue that causes a temporary lock out, the addon just retries and retries, then the WD kills it.

Ended up creating an automation that restarts the addon every 5 min if it isn't up.

**Comment by seevee** [comment] 2024-02-01 17:53
@rbray89 do you mind sharing your automation yaml here? Sounds like a great interim solution to me!

**Comment by wingrunr21** [comment] 2024-02-01 17:55
I'll ping upstream as well.

In the interim, I'll add the solution @rbray89 proposed to not exit the container. I'm also seeing it bomb out and it messes up the energy dashboard cause it dumps a big bunch of usage into a single hour block.

**Comment by rbray89** [comment] 2024-02-03 17:38
@seevee 

`alias: Restart Itron Addon
description: ""
trigger:
  - platform: time_pattern
    minutes: /5
condition:
  - condition: state
    entity_id: binary_sensor.xcel_itron_mqtt_running
    state: "off"
action:
  - service: hassio.addon_start
    metadata: {}
    data:
      addon: 513749ae_xcel-itron-mqtt
mode: single
`

You have to enable the addon status entity, as it is disabled by default.

**Comment by Eschguy** [comment] 2024-02-07 22:50
Updated to `v1.1.0` so we'll see how it goes!

**Comment by kkellner** [comment] 2024-02-09 08:08
Updated to `v1.1.0`.  Looks like the reconnect is working as the container did not have to restart and I'm still getting data.  It would be nice if:
1. The log lines included date as well as time
2. The reconnect log files include date/time

From my logs:

```
[21:08:20] INFO: Starting Xcel iTron2MQTT
s6-rc: info: service legacy-services successfully started
INFO: Connected to MQTT Broker!
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 2.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa76eab7170>, 'Connection to 172.20.0.14 timed out. (connect timeout=15.0)')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Read timed out. (read timeout=15.0).
```

**Comment by wingrunr21** [comment] 2024-02-09 12:55
> Updated to `v1.1.0`. Looks like the reconnect is working as the container did not have to restart and I'm still getting data. It would be nice if:
> 
> 1. The log lines included date as well as time
> 2. The `retrying` log lines included date/time
> 

That'll be another change upstream to put that in the Python logging output. I must admit, I somewhat expected the logging system to handle timestamps.

Your log output would be correct behavior though.

I'm going to give this issue through the weekend and if it is still working for folks I will close it.

**Comment by bmcgowan32** [comment] 2024-02-09 17:03
+1 for the update!  I haven't had to restart the add-on since updating to 1.1.0.  Thanks so much!!!

**Comment by seevee** [comment] 2024-02-09 23:46
Thanks for the update, fixed it for me!

I forced a disconnect by changing the password in launchpad, and everything came back up automatically when I changed it back:

![image](https://github.com/wingrunr21/hassio-xcel-itron-mqtt/assets/4810018/1c4f8d96-f44c-4bf7-9d1e-6f91153be598)

<details>
<summary>
logs:
</summary>

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------

 Add-on: Xcel iTron MQTT
 Bridge from Xcel iTron smart meters to MQTT
-----------------------------------------------------------
 Add-on version: 1.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.1.6
 Home Assistant Supervisor: 2024.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-xcel-itron-mqtt: starting
[12:01:57] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[12:01:58] INFO: Starting Xcel iTron2MQTT
INFO: Connected to MQTT Broker!
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 1.0 seconds as it raised ReadTimeout: HTTPSConnectionPool(host='XCEL_IP', port=8081): Read timed out. (read timeout=15.0).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 2.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb6cd70>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 4.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb762d0>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 8.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb76f90>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 15.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb764b0>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 15.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb77830>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 15.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb77a10>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 15.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb760f0>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 15.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b5c2330>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 15.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b5c0530>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
WARNING: Retrying xcelEndpoint.xcelEndpoint.query_endpoint in 15.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='XCEL_IP', port=8081): Max retries exceeded with url: /upt/1/mr/1/r (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bb77d70>: Failed to establish a new connection: [Errno 113] Host is unreachable')).
```

</details>

**Comment by wingrunr21** [comment] 2024-02-12 17:45
Closing as this seems to be working for folks

**Closed by wingrunr21** 2024-02-12 17:45 UTC
